-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS staging.softcartdimcategory
(
    categoryid integer NOT NULL,
    category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT softcartdimcategory_pkey PRIMARY KEY (categoryid)
);


CREATE TABLE IF NOT EXISTS staging.softcartfactsales
(
    orderid integer NOT NULL,
    dateid integer NOT NULL,
    categoryid integer NOT NULL,
    itemid integer NOT NULL,
    countryid integer NOT NULL,
    price numeric(12, 2) NOT NULL,
    CONSTRAINT softcartfactsales_pkey PRIMARY KEY (orderid)
);


CREATE TABLE IF NOT EXISTS staging.softcartdimcountry
(
    countryid integer NOT NULL,
    country character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT softcartdimcountry_pkey PRIMARY KEY (countryid)
);


CREATE TABLE IF NOT EXISTS staging.softcartdimdate
(
    dateid integer NOT NULL,
    fulldate date NOT NULL,
    day smallint NOT NULL,
    weekday smallint NOT NULL,
    weekdayname character varying(10) COLLATE pg_catalog."default" NOT NULL,
    week smallint NOT NULL,
    month smallint NOT NULL,
    monthname character varying(15) COLLATE pg_catalog."default" NOT NULL,
    quarter smallint NOT NULL,
    year smallint NOT NULL,
    CONSTRAINT softcartdimdate_pkey PRIMARY KEY (dateid)
);


CREATE TABLE IF NOT EXISTS staging.softcartdimitem
(
    itemid integer NOT NULL,
    item character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT softcartdimitem_pkey PRIMARY KEY (itemid)
);


ALTER TABLE IF EXISTS staging.softcartfactsales
    ADD CONSTRAINT softcartfactsales_categoryid_fkey FOREIGN KEY (categoryid)
    REFERENCES staging.softcartdimcategory (categoryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS staging.softcartfactsales
    ADD CONSTRAINT softcartfactsales_countryid_fkey FOREIGN KEY (countryid)
    REFERENCES staging.softcartdimcountry (countryid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS staging.softcartfactsales
    ADD CONSTRAINT softcartfactsales_dateid_fkey FOREIGN KEY (dateid)
    REFERENCES staging.softcartdimdate (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS staging.softcartfactsales
    ADD CONSTRAINT softcartfactsales_itemid_fkey FOREIGN KEY (itemid)
    REFERENCES staging.softcartdimitem (itemid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;
